# Generated by Django 3.2 on 2021-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Store', 'Store'), ('Men', 'Men'), ('badminton', 'badminton'), ('Women', 'Women'), ('Electonic Gadgets', 'Electronic gadgets')], default='Store', max_length=200),
        ),
    ]
